//! Resmî ECharts `area-rainfall` örneğinin sabit veri dizileri.
//!
//! Kaynak: `../echarts-examples` @
//! `1ff3451941535c51af83eacd504035ef4bfd7d0d`.
//! Değerler kayıpsız olarak binde bir ölçekli, delta + zigzag + varint
//! biçiminde kodlanmıştır; böylece 6.158 sayılık fixture okunabilir kalır.

use base64::Engine as _;

const VERİ_SAYISI: usize = 3079;

const AKIŞ_KODU: &str = concat!(
    "lA8TABMAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMTExMTExMAEwAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAUFCg8PDxQPFBQPDw8PDxQPFA8KDwUKAATEyc7O087Tzs7JycTEycTExMTEwATAAAAAAAA",
    "AAAAAAAAAAAAABMAExMTExMTABMTABMTExMTABMAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMT",
    "ExMTExMAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMT",
    "ExMTEwATEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEycnJzs7JycnEwAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEwAAExMAEwATEwATABMAExMAEwAAEwAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAB4rALMA8QElAW8BbwFlAXEBMwDrAJ4AAAAAAAAAAAAAAAAT9sBvwKPA8sD3wPzA8sDjwO/",
    "AtsBTwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNPY4sBnwGzAZ8BnwGLAWNPEwAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATABMAExMTABMAAAAAAAAAAAAAAAAAAAAUKCgoPDwoKCgUAAAAAAAAAAAAAAAAAAAT",
    "JycnOzsnJycTAAAAAAAAAAAAAAAAAAAAFAAUFBQAFAAUAAAAAAAAAAAAAAAAAAAUFCgUKCgUKBQUAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUKBQoKCgoKBQUAAAAAAAAAAAAAAAAAAAAExMTExMTEwATAAAAAAAAAAAAAAAAAAAT",
    "EycnJycTJxMTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFBQUKCgUPCgoPCg8PDwoPDw8PDwoPDwoKCgoKBQoFAAUAAATJyc7OztPT09PY09P",
    "T09PO08nJycTAAAAAAAAAAAAAAAAAAAAFBQUFCgUKCgoPCg8KDwoPDw8KDw8KDwoPCgoKCgUKBQUFBQAFAAUAAAUAAAAFAAA",
    "FAAAFAAUABQUFDygAdwBrALUAvwCpAO4A7gDuAOQA5AD6ALUAtQCrAKsAqwCmAKYAoQChAKYAoQCmAKYApgCrALAAsAC6ALo",
    "AvwCkAO4A8wD4AOIBLAE2ATsBKgFvAX4BaAG3AaEB8AH+AqgFcgkvN4CiKwFjO4HyOYIiHKDDMshxzPHeae+AeftAa+DArv/",
    "Ac/hAaeqAcNjh0WHNocxrzavRc9kj4AB44cBy3vHW/82sy6TKLsjsx/zHJcb7xrTG68d5yCLJJcl2ySbIusdyxe7D88FAAAA",
    "AAAAAAAAAAAAywPXCesOtxKLFZcWlxaLFbcS6w7XCcsDKHi0AfABrALUAvwCpAO4A+AD4APgA+AD4APgA7gDpAP8AtQCrALw",
    "AbQBeCibBNsL0xGXFqcZgxurG4sayxevE/MNgwf7AucC0wLTAqsCqwKXAoMC7wHbAdsBxwGzAZ8BiwGLAWNjYzs7EycAAAAA",
    "ABQAAAAUAAAUAAAUABQAABQAFAAAFAAAFAAAABQAAAAAAAAAAAAAEwAAABMAABMAExMAExMAExMTT8cB2wHvAbMBOwAAAAAA",
    "AAAAAAAAABMAAAAAAAAAAAAAEwAAAAAAAAATAAAAAAATAAAAAAAAEwAAAAAAABMAAAAAAAAAEwAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUFCgUKCgUKBQUAAAAAAAAACh4tAGEAtQCpAPgA5wE7AS8BfgFtAaEB8AH/Ae4",
    "CIgJxAnkFJQovDfcQvRJmE20TMhH1D7YMegg8Av/CccaqyXTKqsqsySnI8MnmyevIv8Y9wqXAu8BxwGLAWMnyAHcBqALgA/U",
    "EdgT6BaoHoQqpDrMTrhnhIECgOgWyEy/swKD/AHLjwGDNOcbsxrTL9PAAbeWAtdok0vTOb801zu3TvNiy3Gje6OAAaOAAbd7",
    "83HDY5NQ60WnRrdEm0DTOd8w5yWvGMsIpFOQtwHMtwGErAGYrAH0bNQ00C2sJZAc1BGMBpsYzzzzTvNO4zzXGDs7JycnJxMT",
    "ExMTABMAAJzdAriIBZzdAr8vg3q7pQHnsQGHnwGvbatIy0STQe893zrjN/s0uzL7L+MtyyvbKZMotyaDJfcj6yKHIqMh5yC/",
    "IKsgqyC/IJMegxuXG5sdhx2LGu8VrxOPEvsR3xKLFbsZux6HIp8klyXbJOsixx/vGvcUyw3rBAAAAAAAAAAAAAAAAHfTApsE",
    "uwWfBpcHqwfTB9MHlwfHBs8FpwW7Bc8FzwXPBacFkwXrBJsE3wP7AqsC2wGzAZ8BiwF3Y3d3d4sBswHHAYMCqwL7Ao8DtwPL",
    "A/MD8wPzA/MD8wPLA8sD8wPzA4cEhwSbBPMD8wPfA8sDowOPA+cCvwKrAqsCgwKXAoMClwKXAqsCvwLTAvsCtwPLA98DhwTz",
    "A/MD3wPLA6MD5wKrApcCgwKXAoMCgwLvAccBxwGLAXdPE5QFnA7cFdQbhCDsIvgj0CO4IewdxBjoEeANzA24DZAN/AzADKwM",
    "3Au0C/gKvAqACpwJ4AiQCKwH3AbkBZQFnASkA8ACyAE82wGTBY8I9wqjDbsPlxHzEv8T9xTHFe8V7xXbFYsVkxTzEr8Rzw/L",
    "DZ8Lywi7BZcCOycTJxMTExMTJyc7xwHfA5MF2wbTB6MIywjfCKMIvwfHBqcFrwTzA/MDywO3A48DowP7AvsC+wKPA/sC+wKP",
    "A+cC+wLnAucC5wLTAtMC0wLTAr8CvwLTAr8CvwK/Ar8CqwKrApcCgwLvAe8B2wGzAccBnwGzAZ8BnwGfAZ8BnwGzAbMBswHH",
    "AccBxwHHAdsBxwHHAccBxwHHAccBxwHvAe8B7wHvAe8B2wHHAZ8Bd2MTAAAAAAAAAAAAAAAAJ093swGzAccBxwGzAbMBd08n",
    "AAAAAAAAAAAAAAAAJ093swGzAdsBxwHbAccBnwGLAWNPOztPOzs7Tzs7Jzs7JzsnOycnJycnEycnExMTExMTABMAEwAUFCg8",
    "PDw8KDwoFBQAAAATAAATAAATABMAABMAEwAAABMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "FAAAFAAUFBQAFBQoFBQUKCgUKCgoKDwoPCg8PDw8UDyYAqgFzAjwC5QPpBLcFYAZkBzIH+wipCaIWegHoBqYXOBTiGio5gHI",
    "wATYpgKIpAGwbZ8Gz6UBqBT3PKgUqBSwVJikAqixB6D+CuCJA+CPAfC7BO/dAf8xAI/hApBn38EB/64BAAAA/64BgDLvqALP",
    "KO95oAbvjwKHugK33wGPsgHXHdcd/+AB36gBr1Sv0QG/V5+DAc8Pp0bnnQHPQe+SAfc8/2PHTKMwv/cBk/ABnMcBsz3XO/8T",
    "rxPfJgCwE/eqAdjRAb9Nt2z3HvceALMuALsPnynfRI8S0C2AN79S/3fHC8cLnyn4S/dLAADQFM8UpwqQP4deoCn3HqcKzxQA",
    "AL8RnxrfCL8RpxnnBwAA0A/PD7A73ysAj06/GwAAAAAAAAAAAPcP9w88oAGYApADnASoBaAG1AfgCIAKoAvoDIgO0A+YEcwS",
    "qBSEFswXvBmsG4gdjB/8IJQjhCWcJ7QpzCv4LaQwvDL8NLw3/DnQPPTuAdSGAsAM8EeoFKcUrzu/DL8lxzPHLugb43jjbpxA",
    "k2n3KLsUALM9vBSHIqM/hyK4IbAT3ybfJo869x6zLrMu1yzfDb9S13eYXK9FxwunN+ArxwvHCwDYIgDYIu9qqB6oHscL7xWn",
    "CqcK9x7PFAAAzzffCLBAt7IBwD7PD+gHALcX6AegQgDgCADfCOAI3wjgCJ8awBG3OugH6AfnB88Pt0nQQZ8fr0+AXwDPD/c8",
    "twjnB5cHxwb3BbsF/wSvBPMDywP7AtMCqwLvAdsBnwGLAWNPJycA/CWjNawv/wSzC9MMjwjzA7cD+wLTApcCgwLvAe8B7wHv",
    "AYMClwK/AtMC5wLnAo8D+wKPA48DowOPA/sC+wL7AucCvwK/ApcCgwLvAccBiwF3TxP0CKAVqBmgFfQIlwLnAnd3Y2NjY09P",
    "Tzs7Oyc7JxMnExMAEwCUBagPO7MBgwL7AssDrwTXBKcF4wWLBrMGxwbvBu8GgwfvBu8G2wazBp8G4wW7Bf8ErwTzA48DvwLH",
    "AWMnEycnJxMnEycTEycTExMTExMTExMTEwATABMAEwAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAUAAAAAAAUAAAAFAAAAAAUAAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExMTJxMnJxMTEwAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMAABMAExMTABMTABMTEwATAAATAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFBQUFCgoKDwoPDw8PDw8UDw8UDw8",
    "PDw8PDwoKCgoFBQUFAAAEycnOzs7T09PT09PT09PTzs7OycnEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAABMAEwATABMTAAATABMAABMAABMAABMAABMAAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAU",
    "AAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAUAAAAAAAUAAAAAAAUAAA=",
);

const YAĞIŞ_KODU: &str = concat!(
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAChgAAAALFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoKCAwAvgI0kwMLCBoAACABDVxNAA8FAgIQEAd6lwEHFgQAAD4G",
    "GwgAEipADQ4YrAGlAVudASMAAAAAJDoOAAAjqgLfAjouIBxG6Aj3B84C6wGpASNOhQExBwBc1QEPAAMAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKKhgAAEwULtABfhgSsgWKEuUIjA6BE88G+AKeAsMGswYAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkDAAAACMFVgAAAAVVAAAAAAAAAAAAAAAA",
    "AAAAAACYA8YBqgvYBIgD4wFfiwHJAasKN/YGxA2CEe8fuQtNT10AAAAWIgAAABUhAAAAAAAAAAAAAAAAAAAAxgF4lAIYAOIE",
    "mAPUCeEDgwoVugZx3wafAdQCzwLNAjkACSkc9AGfAqkCAAAAAAMNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDgA",
    "AABkhgFuVh7IAyguqgPKAZQY6RKTAf0J3wZVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIACCpKQB4H",
    "FpILzwsxExVlCQAAAAAAAAAAAAAAABYMAAAAFQsAAAAAFCgwGgboAgLmA9kGFQAUKA0wPugB5QJgAzfeA8MENQAAAAAJBwAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgmAgAA+gKrAp0BAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAALlwaAADKBp4EvwszAAAICBAuEgj8AU8cMRFZaw8BHQMABwEoOAAKBic3AAcHAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaCCZANpQCTtIBsgWI",
    "DKwj4yuFCAYosQH3AUXjAW8NGykDAAAAAAAoCAAAACcHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEgA4mgL0AYUBAJgKzDHWBpII4Re5FosK6QrtBLsBNNwS3wbtDaMB0wExCQAA",
    "AAAAAAAAAAAAAAAAAAAASrYG4AvaAQDoAZMD3wvQBK8FqwKWAtQDyQLjA9cBhQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABY",
    "1AGSAcoC+gHkBbIezB6qEuEPmBflAbEuvwjsFfEr9wUA5QK/ASfRAZMCuQSjAk0AAAAAAAACBQAAAAkAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFgAAAAEVAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEFCAAANwBWxMAHN4J5wjhAQqkAdcBAA0JKEwqDgBWXXUNACsFAAAAAAAAAAAA",
    "AAAEVu4CigE4HOQDrgr/Bq0EwwTbAl0LAAAAAAAAAAAGBAAAAJgBYIECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABw2AAAAGzUAAAAAAAAAAAAAAAAAAAASEAAAAKQF6QLJAgAG+AGQAQAADtBv",
    "+VXvFakGAAsDAByaAWgkCPQFwg6uRucUlwSnO9MEQoQDtAVStB+CZZ0550jHD3kRDwUHAAAVAAAAAAAAAAAAAHCsA1hKBv4D",
    "9gLKEOEP6wSHBUcALjwHWvoBaugI3h2zE/MYKwCyAZEBAAa8AsgIAAAAVeMJcQAAORsAAAAFB6gJ+gWABZAP/gP/AsACrQPn",
    "DfgElBjXIMsGiQP8B+sFWJ8FqQPQAQDiAvcFJgAAAlYLygGeAW1J7gjbBbsBjQGtAiESigHyAagDygHoEcgLkQjDGb0CsAEh",
    "Na4CF6kCA3bZAS0OwgOSBZcGlAKtBMMBBQAAAwckGhrmAb4JjQtiyQEzJwUBAAAqAAAAAA8AAAAAAAAABQAAAAAAAAAAAAMP",
    "AAAAAAAAAAAAAAAAAAAAACQGAAAAIwUAAAAAAAAAADCqArABDACWBOgMxAa3EOsHjwMAFBAHxALfAV32A4UEFgAVCw0bAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAgAcIAcaYFo8NPYBvAq3B+IUqB2LB9kQlRDFAtoC7QYCiAWXAvsD2wKD",
    "Ac8BY60CjgfrBbACnCGdJgNBAAAAArwBlQEDAAImAAQEAzkAAAAAAAAiHiJwFx0NJwkLFwUOAx8ADw0AAAAGIAEAAAUhAAAA",
    "ABgCAAAJBwAAAAAAAwUAAAAAAAAAAAARAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAFgwOBEbeAUQObOgDugL9B5cCAAA6EGsAAAAAAAAAAAAAAAAAAAIgAAAAAR8AAAAAAAAAABQOAAAACQoAAAAJFwAAAAAG",
    "OEY2JhSgAYsCNSUVFQAAAAAAAAAAAAAEBg4SAAMcBQcAEHqNAQAAAQcBAAANJh4BAAArGR4SAAARHREAAAAAAAYcAAAABRsA",
    "AAAAQAAAAAA1BgIKAAkHAQcAAAAAAAAAAAAAAAAAAAAADgQAAABEKCocBuAB8gFiXiR+xAREzgw36wEAJ68GlQmJBMkBJzkE",
    "ERqAAYIBlgEiBuYCnAa6A4IIJHIAbc0BnAW9AtcCsgqRHCpKpgT6AooB8ALSD5ANywGQBocerQkqqAK4Ab8C7QHICdwEAAye",
    "AjvtCfUF7Qh/AADNAWEAAOoBFAAAAAD9AQAAAAAAAAAAAAAAAAAAAAAAAAAGBAAAAAMFAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqBG4AAADZBGkAAAQGAL4B8AakBAII4ghOrQGwAZwD",
    "ogHEBogBuA/RArEWsQtpwwJjDT0JngvlCD1fqgH9B4sBjwECVyMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACjgG0A6gCuAE2+ATMAgL/DL0CYQAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwS",
    "AAAAdrMBAQAAAAAAAAAAYgwGAAAj0gJQdqoBzAFpKsoB5gOmBfUF9wjnARUHTRkfAgAAAAAABoIBogHOAWTEAcwERrQB1wGv",
    "Ar0C3QGXAQcVALgBtAa6AeQIgwT5BZsDMtEBWQMBFQtjnwFvXZMBE1guAAkaCg48LK4BL08uH5sBGwcfERk1KxEAASgKAHQc",
    "LQkAcyUAAAsTNhgICjiAAUwLCStJrQExAAAAAAAAIB4AAAAfHQAAAAAKAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAHAQAA",
);

pub fn verileri_çöz() -> Result<(Vec<f64>, Vec<f64>), String> {
    Ok((
        binde_bir_delta_verisini_çöz("Flow", AKIŞ_KODU)?,
        binde_bir_delta_verisini_çöz("Rainfall", YAĞIŞ_KODU)?,
    ))
}

fn binde_bir_delta_verisini_çöz(ad: &str, kod: &str) -> Result<Vec<f64>, String> {
    let baytlar = base64::engine::general_purpose::STANDARD
        .decode(kod.as_bytes())
        .map_err(|hata| format!("{ad} fixture verisi base64 çözülemedi: {hata}"))?;
    let mut sonuç = Vec::with_capacity(VERİ_SAYISI);
    let mut önceki = 0_i64;
    let mut sıra = 0_usize;

    while sıra < baytlar.len() {
        let mut zigzag = 0_u64;
        let mut kaydırma = 0_u32;
        loop {
            let bayt = *baytlar
                .get(sıra)
                .ok_or_else(|| format!("{ad} fixture verisinde yarım varint"))?;
            sıra += 1;
            if kaydırma >= 64 || (kaydırma == 63 && bayt & 0x7e != 0) {
                return Err(format!("{ad} fixture verisinde taşan varint"));
            }
            zigzag |= u64::from(bayt & 0x7f) << kaydırma;
            if bayt & 0x80 == 0 {
                break;
            }
            kaydırma += 7;
        }

        let büyüklük = i64::try_from(zigzag >> 1)
            .map_err(|_| format!("{ad} fixture deltası i64 sınırını aşıyor"))?;
        let fark = if zigzag & 1 == 0 {
            büyüklük
        } else {
            -büyüklük - 1
        };
        önceki = önceki
            .checked_add(fark)
            .ok_or_else(|| format!("{ad} fixture toplamı i64 sınırını aşıyor"))?;
        sonuç.push(önceki as f64 / 1_000.0);
    }

    if sonuç.len() != VERİ_SAYISI {
        return Err(format!(
            "{ad} fixture uzunluğu {} olmalıydı, {} bulundu",
            VERİ_SAYISI,
            sonuç.len()
        ));
    }
    Ok(sonuç)
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod testler {
    use super::*;

    #[test]
    fn resmi_diziler_kayipsiz_cozulur() {
        let (akış, yağış) = verileri_çöz().expect("fixture çözülmeli");
        assert_eq!(akış.len(), 3_079);
        assert_eq!(yağış.len(), 3_079);
        assert_eq!(akış.iter().copied().reduce(f64::max), Some(365.0));
        assert_eq!(yağış.iter().copied().reduce(f64::max), Some(9.415));
    }
}
